name: pantrythief
description: "Your own pantry and recipe helper"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0-323.1.beta

dependencies:
  flutter:
    sdk: flutter
  
  flutter_hooks:
  cupertino_icons:
  google_fonts:
  dartz:
  equatable:
  flutter_bloc:
  get_it:
  shared_preferences:
  flutter_riverpod:
  riverpod_annotation:
  units_converter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mockito:
  mocktail:
  bloc_test:
  riverpod_generator:
  custom_lint:
  riverpod_lint:

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
