name: pantrythief
description: "Your own pantry and recipe helper"

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.5.0-323.1.beta

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons:
  google_fonts:
  dartz:
  equatable:
  flutter_bloc:
  get_it:
  shared_preferences:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mockito:
  mocktail:
  bloc_test:

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
